version: '3.8'
services:
  backendapi:
    #image: backendapiolanda
    build:
      dockerfile: dockerfile
      context: .
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://user:password@192.168.0.3:3306
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8088:3000'
    networks:
      context:
        ipv4_address: '192.168.0.1'
  mysql:
    image: mariadb
      container_name: olanda_mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'Pass2021'
        MYSQL_DATABASE: 'olanda'
        MYSQL_USER: 'olanda'
        MYSQL_PASSWORD: 'PPass2021'
      volumes:
        - $PWD/mysql-data:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        context:
          ipv4_address: '192.168.0.3'
   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: processify_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      context:
        ipv4_address: '192.168.0.2'
networks:
  context:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/28
